require 'rubygems'
require 'gdata'
require 'cgi'
require 'net/http'
require 'net/https'
require 'rubygems'
require 'hpricot'
require 'time'
require 'zlib'
require 'stringio'
require 'yaml'
require 'uri'
require 'md5'
require 'crack'

require File.expand_path(File.dirname(__FILE__) + '/../lib/contacts_rails')
